version: '3.1'

services:
  backend:
    env_file:
      - ./.env
    build:
      context: .
    ports:
      - "8080:8080"
    command: bash -c "
      python manage.py migrate
      && gunicorn atrucks.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
  db:
    image: postgres:13.1
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

volumes:
  pgdata: