# Generated by Django 5.0.1 on 2024-02-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code number')),
                ('from_limit', models.IntegerField(verbose_name='From limit')),
                ('to_limit', models.IntegerField(verbose_name='To limit')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('operator', models.CharField(max_length=125, verbose_name='Numbers operator')),
                ('region', models.CharField(max_length=125, verbose_name='Region')),
                ('inn', models.CharField(max_length=125, verbose_name='INN')),
            ],
            options={
                'db_table': 'open_data',
            },
        ),
    ]
