# Generated by Django 4.2.9 on 2024-02-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendata',
            name='inn',
            field=models.CharField(max_length=500, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='operator',
            field=models.CharField(max_length=500, verbose_name='Numbers operator'),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='region',
            field=models.CharField(max_length=500, verbose_name='Region'),
        ),
    ]
